[package]
name = "safe_drive"
version = "0.1.0"
edition = "2021"
authors = ["Yuuki Takano <yuuki.takano@tier4.com>"]

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
num-traits = "0.2"
num-derive = "0.3"
once_cell = "1.14"
crossbeam-channel = "0.5"
parking_lot = "0.12"
signal-hook = "0.3"
ctor = "0.1"

[dependencies.serde]
version = "1"
features = ["derive"]
optional = true

[dependencies.serde_json]
version = "1"
optional = true

[dependencies.memac]
version = "0.3"
optional = true

[dev-dependencies]
futures = "0.3"

[dev-dependencies.async-std]
version = "1.12"
features = ["attributes"]

[features]
default = []
statistics = ["serde", "serde_json"]
rcl_stat = ["statistics"]
humble = []
galactic = []
custom_alloc = ["memac"]
